#mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.zzx.dao
  global-config:
    banner: false
    db-config:
      table-prefix: tbl_
  mapper-locations: classpath:mapper/*.xml

#数据库配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/vue
      username: root
      password: JXLZZX79
      driver-class-name: com.mysql.cj.jdbc.Driver

#日志信息
logging:
  level:
    root: error

server:
  port: 8888